parameters:
    applications:
        # Backoffice app definition
        manager:
            title: Mapbender Administration
            template:  Mapbender\ManagerBundle\Template\ManagerTemplate
            excludeFromList: true
            published: true
            roles: [IS_AUTHENTICATED_ANONYMOUSLY]

        # Login app definition
        mb3-login:
            title: Mapbender Login
            template:  Mapbender\ManagerBundle\Template\LoginTemplate
            excludeFromList: true
            published: true
            anonymous: true
            roles: [IS_AUTHENTICATED_ANONYMOUSLY]

    mapbender.branding.name: Mapbender
    mapbender.version: 3.0.8.1
    mapbender.branding.logo: bundles/mapbendercore/image/logo_mb3.png
    # These should all remain empty here, they are just for IDE search results.
    # Customize these in your parameters.yml.
    # The name will show up in page titles; the version will show in your backend;
    # the logo will display on your login page, the backend again, and some of the application templates.
    branding.project_name: ~
    branding.project_version: ~
    branding.logo: ~                # web-relative path

    # Sitelinks displayed below login box and backend content
    # Should be a list of items each with keys 'link' and 'text'
    mapbender.sitelinks: []
