<?php

namespace Proxies\__CG__\Mapbender\WmsBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class WmsSource extends \Mapbender\WmsBundle\Entity\WmsSource implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'originUrl', 'name', 'version', 'onlineResource', 'contact', 'fees', 'accessConstraints', 'layerLimit', 'maxWidth', 'maxHeight', 'exceptionFormats', 'supportSld', 'userLayer', 'userStyle', 'remoteWfs', 'inlineFeature', 'remoteWcs', 'getCapabilities', 'getMap', 'getFeatureInfo', 'describeLayer', 'getLegendGraphic', 'getStyles', 'putStyles', 'username', 'password', 'layers', 'keywords', 'instances', 'id', 'title', 'alias', 'valid', 'description', 'type', 'identifier'];
        }

        return ['__isInitialized__', 'originUrl', 'name', 'version', 'onlineResource', 'contact', 'fees', 'accessConstraints', 'layerLimit', 'maxWidth', 'maxHeight', 'exceptionFormats', 'supportSld', 'userLayer', 'userStyle', 'remoteWfs', 'inlineFeature', 'remoteWcs', 'getCapabilities', 'getMap', 'getFeatureInfo', 'describeLayer', 'getLegendGraphic', 'getStyles', 'putStyles', 'username', 'password', 'layers', 'keywords', 'instances', 'id', 'title', 'alias', 'valid', 'description', 'type', 'identifier'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (WmsSource $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setOriginUrl($originUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOriginUrl', [$originUrl]);

        return parent::setOriginUrl($originUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getOriginUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOriginUrl', []);

        return parent::getOriginUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setVersion($version)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVersion', [$version]);

        return parent::setVersion($version);
    }

    /**
     * {@inheritDoc}
     */
    public function getVersion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVersion', []);

        return parent::getVersion();
    }

    /**
     * {@inheritDoc}
     */
    public function setOnlineResource($onlineResource)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOnlineResource', [$onlineResource]);

        return parent::setOnlineResource($onlineResource);
    }

    /**
     * {@inheritDoc}
     */
    public function getOnlineResource()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOnlineResource', []);

        return parent::getOnlineResource();
    }

    /**
     * {@inheritDoc}
     */
    public function setContact($contact)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContact', [$contact]);

        return parent::setContact($contact);
    }

    /**
     * {@inheritDoc}
     */
    public function getContact()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContact', []);

        return parent::getContact();
    }

    /**
     * {@inheritDoc}
     */
    public function setFees($fees)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFees', [$fees]);

        return parent::setFees($fees);
    }

    /**
     * {@inheritDoc}
     */
    public function getFees()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFees', []);

        return parent::getFees();
    }

    /**
     * {@inheritDoc}
     */
    public function setAccessConstraints($accessConstraints)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccessConstraints', [$accessConstraints]);

        return parent::setAccessConstraints($accessConstraints);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccessConstraints()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccessConstraints', []);

        return parent::getAccessConstraints();
    }

    /**
     * {@inheritDoc}
     */
    public function setLayerLimit($layerLimit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLayerLimit', [$layerLimit]);

        return parent::setLayerLimit($layerLimit);
    }

    /**
     * {@inheritDoc}
     */
    public function getLayerLimit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLayerLimit', []);

        return parent::getLayerLimit();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaxWidth($maxWidth)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaxWidth', [$maxWidth]);

        return parent::setMaxWidth($maxWidth);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaxWidth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaxWidth', []);

        return parent::getMaxWidth();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaxHeight($maxHeight)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaxHeight', [$maxHeight]);

        return parent::setMaxHeight($maxHeight);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaxHeight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaxHeight', []);

        return parent::getMaxHeight();
    }

    /**
     * {@inheritDoc}
     */
    public function setExceptionFormats($exceptionFormats)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExceptionFormats', [$exceptionFormats]);

        return parent::setExceptionFormats($exceptionFormats);
    }

    /**
     * {@inheritDoc}
     */
    public function addExceptionFormat($exceptionFormat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addExceptionFormat', [$exceptionFormat]);

        return parent::addExceptionFormat($exceptionFormat);
    }

    /**
     * {@inheritDoc}
     */
    public function getExceptionFormats()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExceptionFormats', []);

        return parent::getExceptionFormats();
    }

    /**
     * {@inheritDoc}
     */
    public function setSupportSld($supportSld)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSupportSld', [$supportSld]);

        return parent::setSupportSld($supportSld);
    }

    /**
     * {@inheritDoc}
     */
    public function getSupportSld()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSupportSld', []);

        return parent::getSupportSld();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserLayer($userLayer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserLayer', [$userLayer]);

        return parent::setUserLayer($userLayer);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserLayer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserLayer', []);

        return parent::getUserLayer();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserStyle($userStyle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserStyle', [$userStyle]);

        return parent::setUserStyle($userStyle);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserStyle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserStyle', []);

        return parent::getUserStyle();
    }

    /**
     * {@inheritDoc}
     */
    public function setRemoteWfs($remoteWfs = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRemoteWfs', [$remoteWfs]);

        return parent::setRemoteWfs($remoteWfs);
    }

    /**
     * {@inheritDoc}
     */
    public function getRemoteWfs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRemoteWfs', []);

        return parent::getRemoteWfs();
    }

    /**
     * {@inheritDoc}
     */
    public function setInlineFeature($inlineFeature = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInlineFeature', [$inlineFeature]);

        return parent::setInlineFeature($inlineFeature);
    }

    /**
     * {@inheritDoc}
     */
    public function getInlineFeature()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInlineFeature', []);

        return parent::getInlineFeature();
    }

    /**
     * {@inheritDoc}
     */
    public function setRemoteWcs($remoteWcs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRemoteWcs', [$remoteWcs]);

        return parent::setRemoteWcs($remoteWcs);
    }

    /**
     * {@inheritDoc}
     */
    public function getRemoteWcs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRemoteWcs', []);

        return parent::getRemoteWcs();
    }

    /**
     * {@inheritDoc}
     */
    public function setGetCapabilities(\Mapbender\WmsBundle\Component\RequestInformation $getCapabilities = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGetCapabilities', [$getCapabilities]);

        return parent::setGetCapabilities($getCapabilities);
    }

    /**
     * {@inheritDoc}
     */
    public function getGetCapabilities()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGetCapabilities', []);

        return parent::getGetCapabilities();
    }

    /**
     * {@inheritDoc}
     */
    public function setGetMap(\Mapbender\WmsBundle\Component\RequestInformation $getMap = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGetMap', [$getMap]);

        return parent::setGetMap($getMap);
    }

    /**
     * {@inheritDoc}
     */
    public function getGetMap()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGetMap', []);

        return parent::getGetMap();
    }

    /**
     * {@inheritDoc}
     */
    public function setGetFeatureInfo(\Mapbender\WmsBundle\Component\RequestInformation $getFeatureInfo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGetFeatureInfo', [$getFeatureInfo]);

        return parent::setGetFeatureInfo($getFeatureInfo);
    }

    /**
     * {@inheritDoc}
     */
    public function getGetFeatureInfo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGetFeatureInfo', []);

        return parent::getGetFeatureInfo();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescribeLayer(\Mapbender\WmsBundle\Component\RequestInformation $describeLayer = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescribeLayer', [$describeLayer]);

        return parent::setDescribeLayer($describeLayer);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescribeLayer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescribeLayer', []);

        return parent::getDescribeLayer();
    }

    /**
     * {@inheritDoc}
     */
    public function setGetLegendGraphic(\Mapbender\WmsBundle\Component\RequestInformation $getLegendGraphic = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGetLegendGraphic', [$getLegendGraphic]);

        return parent::setGetLegendGraphic($getLegendGraphic);
    }

    /**
     * {@inheritDoc}
     */
    public function getGetLegendGraphic()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGetLegendGraphic', []);

        return parent::getGetLegendGraphic();
    }

    /**
     * {@inheritDoc}
     */
    public function setGetStyles(\Mapbender\WmsBundle\Component\RequestInformation $getStyles = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGetStyles', [$getStyles]);

        return parent::setGetStyles($getStyles);
    }

    /**
     * {@inheritDoc}
     */
    public function getGetStyles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGetStyles', []);

        return parent::getGetStyles();
    }

    /**
     * {@inheritDoc}
     */
    public function setPutStyles(\Mapbender\WmsBundle\Component\RequestInformation $putStyles = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPutStyles', [$putStyles]);

        return parent::setPutStyles($putStyles);
    }

    /**
     * {@inheritDoc}
     */
    public function getPutStyles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPutStyles', []);

        return parent::getPutStyles();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername($username)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', [$username]);

        return parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', []);

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setLayers($layers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLayers', [$layers]);

        return parent::setLayers($layers);
    }

    /**
     * {@inheritDoc}
     */
    public function getLayers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLayers', []);

        return parent::getLayers();
    }

    /**
     * {@inheritDoc}
     */
    public function addLayer(\Mapbender\WmsBundle\Entity\WmsLayerSource $layer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLayer', [$layer]);

        return parent::addLayer($layer);
    }

    /**
     * {@inheritDoc}
     */
    public function getRootlayer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRootlayer', []);

        return parent::getRootlayer();
    }

    /**
     * {@inheritDoc}
     */
    public function setKeywords(\Doctrine\Common\Collections\ArrayCollection $keywords)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKeywords', [$keywords]);

        return parent::setKeywords($keywords);
    }

    /**
     * {@inheritDoc}
     */
    public function getKeywords()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKeywords', []);

        return parent::getKeywords();
    }

    /**
     * {@inheritDoc}
     */
    public function addKeyword(\Mapbender\CoreBundle\Entity\Keyword $keyword)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addKeyword', [$keyword]);

        return parent::addKeyword($keyword);
    }

    /**
     * {@inheritDoc}
     */
    public function addInstance(\Mapbender\WmsBundle\Entity\WmsInstance $instance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addInstance', [$instance]);

        return parent::addInstance($instance);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLayer(\Mapbender\WmsBundle\Entity\WmsLayerSource $layers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLayer', [$layers]);

        return parent::removeLayer($layers);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdentifier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdentifier', []);

        return parent::getIdentifier();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdentifier($identifier)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdentifier', [$identifier]);

        return parent::setIdentifier($identifier);
    }

    /**
     * {@inheritDoc}
     */
    public function dimensionInstancesFactory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'dimensionInstancesFactory', []);

        return parent::dimensionInstancesFactory();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlias($alias)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlias', [$alias]);

        return parent::setAlias($alias);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlias()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlias', []);

        return parent::getAlias();
    }

    /**
     * {@inheritDoc}
     */
    public function getClassname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClassname', []);

        return parent::getClassname();
    }

    /**
     * {@inheritDoc}
     */
    public function setValid($valid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValid', [$valid]);

        return parent::setValid($valid);
    }

    /**
     * {@inheritDoc}
     */
    public function getValid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValid', []);

        return parent::getValid();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getManagertype()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getManagertype', []);

        return parent::getManagertype();
    }

}
