<?php

namespace Proxies\__CG__\Mapbender\WmsBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class WmsLayerSource extends \Mapbender\WmsBundle\Entity\WmsLayerSource implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'source', 'parent', 'sublayer', 'name', 'title', 'abstract', 'queryable', 'cascaded', 'opaque', 'noSubset', 'fixedWidth', 'fixedHeight', 'latlonBounds', 'boundingBoxes', 'srs', 'styles', 'scale', 'scaleHint', 'attribution', 'identifier', 'authority', 'metadataUrl', 'dimension', 'dataUrl', 'featureListUrl', 'keywords', 'priority', 'instanceLayers'];
        }

        return ['__isInitialized__', 'id', 'source', 'parent', 'sublayer', 'name', 'title', 'abstract', 'queryable', 'cascaded', 'opaque', 'noSubset', 'fixedWidth', 'fixedHeight', 'latlonBounds', 'boundingBoxes', 'srs', 'styles', 'scale', 'scaleHint', 'attribution', 'identifier', 'authority', 'metadataUrl', 'dimension', 'dataUrl', 'featureListUrl', 'keywords', 'priority', 'instanceLayers'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (WmsLayerSource $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSource(\Mapbender\CoreBundle\Entity\Source $wmssource)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSource', [$wmssource]);

        return parent::setSource($wmssource);
    }

    /**
     * {@inheritDoc}
     */
    public function getSource()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSource', []);

        return parent::getSource();
    }

    /**
     * {@inheritDoc}
     */
    public function setParent(\Mapbender\WmsBundle\Entity\WmsLayerSource $parent = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParent', [$parent]);

        return parent::setParent($parent);
    }

    /**
     * {@inheritDoc}
     */
    public function getParent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParent', []);

        return parent::getParent();
    }

    /**
     * {@inheritDoc}
     */
    public function getSublayer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSublayer', []);

        return parent::getSublayer();
    }

    /**
     * {@inheritDoc}
     */
    public function setSublayer($sublayer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSublayer', [$sublayer]);

        return parent::setSublayer($sublayer);
    }

    /**
     * {@inheritDoc}
     */
    public function addSublayer(\Mapbender\WmsBundle\Entity\WmsLayerSource $sublayer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSublayer', [$sublayer]);

        return parent::addSublayer($sublayer);
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setAbstract($abstract = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAbstract', [$abstract]);

        return parent::setAbstract($abstract);
    }

    /**
     * {@inheritDoc}
     */
    public function getAbstract()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbstract', []);

        return parent::getAbstract();
    }

    /**
     * {@inheritDoc}
     */
    public function setQueryable($queryable)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQueryable', [$queryable]);

        return parent::setQueryable($queryable);
    }

    /**
     * {@inheritDoc}
     */
    public function getQueryable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQueryable', []);

        return parent::getQueryable();
    }

    /**
     * {@inheritDoc}
     */
    public function setCascaded($cascaded)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCascaded', [$cascaded]);

        return parent::setCascaded($cascaded);
    }

    /**
     * {@inheritDoc}
     */
    public function getCascaded()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCascaded', []);

        return parent::getCascaded();
    }

    /**
     * {@inheritDoc}
     */
    public function setOpaque($opaque)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOpaque', [$opaque]);

        return parent::setOpaque($opaque);
    }

    /**
     * {@inheritDoc}
     */
    public function getOpaque()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOpaque', []);

        return parent::getOpaque();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoSubset($noSubset)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoSubset', [$noSubset]);

        return parent::setNoSubset($noSubset);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoSubset()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoSubset', []);

        return parent::getNoSubset();
    }

    /**
     * {@inheritDoc}
     */
    public function setFixedWidth($fixedWidth = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFixedWidth', [$fixedWidth]);

        return parent::setFixedWidth($fixedWidth);
    }

    /**
     * {@inheritDoc}
     */
    public function getFixedWidth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFixedWidth', []);

        return parent::getFixedWidth();
    }

    /**
     * {@inheritDoc}
     */
    public function setFixedHeight($fixedHeight = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFixedHeight', [$fixedHeight]);

        return parent::setFixedHeight($fixedHeight);
    }

    /**
     * {@inheritDoc}
     */
    public function getFixedHeight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFixedHeight', []);

        return parent::getFixedHeight();
    }

    /**
     * {@inheritDoc}
     */
    public function setLatlonBounds(\Mapbender\CoreBundle\Component\BoundingBox $latlonBounds = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLatlonBounds', [$latlonBounds]);

        return parent::setLatlonBounds($latlonBounds);
    }

    /**
     * {@inheritDoc}
     */
    public function getLatlonBounds($inherit = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLatlonBounds', [$inherit]);

        return parent::getLatlonBounds($inherit);
    }

    /**
     * {@inheritDoc}
     */
    public function addBoundingBox(\Mapbender\CoreBundle\Component\BoundingBox $boundingBoxes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBoundingBox', [$boundingBoxes]);

        return parent::addBoundingBox($boundingBoxes);
    }

    /**
     * {@inheritDoc}
     */
    public function setBoundingBoxes($boundingBoxes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBoundingBoxes', [$boundingBoxes]);

        return parent::setBoundingBoxes($boundingBoxes);
    }

    /**
     * {@inheritDoc}
     */
    public function getBoundingBoxes($inherit = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBoundingBoxes', [$inherit]);

        return parent::getBoundingBoxes($inherit);
    }

    /**
     * {@inheritDoc}
     */
    public function setSrs($srs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSrs', [$srs]);

        return parent::setSrs($srs);
    }

    /**
     * {@inheritDoc}
     */
    public function addSrs($srs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSrs', [$srs]);

        return parent::addSrs($srs);
    }

    /**
     * {@inheritDoc}
     */
    public function getSrs($inherit = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSrs', [$inherit]);

        return parent::getSrs($inherit);
    }

    /**
     * {@inheritDoc}
     */
    public function addStyle(\Mapbender\WmsBundle\Component\Style $style = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addStyle', [$style]);

        return parent::addStyle($style);
    }

    /**
     * {@inheritDoc}
     */
    public function setStyles($styles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStyles', [$styles]);

        return parent::setStyles($styles);
    }

    /**
     * {@inheritDoc}
     */
    public function getStyles($inherit = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStyles', [$inherit]);

        return parent::getStyles($inherit);
    }

    /**
     * {@inheritDoc}
     */
    public function setScale(\Mapbender\WmsBundle\Component\MinMax $scale = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setScale', [$scale]);

        return parent::setScale($scale);
    }

    /**
     * {@inheritDoc}
     */
    public function getScale()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getScale', []);

        return parent::getScale();
    }

    /**
     * {@inheritDoc}
     */
    public function getMinScale($recursive = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMinScale', [$recursive]);

        return parent::getMinScale($recursive);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaxScale($recursive = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaxScale', [$recursive]);

        return parent::getMaxScale($recursive);
    }

    /**
     * {@inheritDoc}
     */
    public function getScaleRecursive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getScaleRecursive', []);

        return parent::getScaleRecursive();
    }

    /**
     * {@inheritDoc}
     */
    public function setScaleHint(\Mapbender\WmsBundle\Component\MinMax $scaleHint = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setScaleHint', [$scaleHint]);

        return parent::setScaleHint($scaleHint);
    }

    /**
     * {@inheritDoc}
     */
    public function getScaleHint()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getScaleHint', []);

        return parent::getScaleHint();
    }

    /**
     * {@inheritDoc}
     */
    public function setAttribution(\Mapbender\WmsBundle\Component\Attribution $attribution = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttribution', [$attribution]);

        return parent::setAttribution($attribution);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttribution()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttribution', []);

        return parent::getAttribution();
    }

    /**
     * {@inheritDoc}
     */
    public function addIdentifier(\Mapbender\WmsBundle\Component\Identifier $identifier = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIdentifier', [$identifier]);

        return parent::addIdentifier($identifier);
    }

    /**
     * {@inheritDoc}
     */
    public function setIdentifier($identifier)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdentifier', [$identifier]);

        return parent::setIdentifier($identifier);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdentifier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdentifier', []);

        return parent::getIdentifier();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdentifierAuthority()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdentifierAuthority', []);

        return parent::getIdentifierAuthority();
    }

    /**
     * {@inheritDoc}
     */
    public function addAuthority(\Mapbender\WmsBundle\Component\Authority $authority)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAuthority', [$authority]);

        return parent::addAuthority($authority);
    }

    /**
     * {@inheritDoc}
     */
    public function setAuthority($authority)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAuthority', [$authority]);

        return parent::setAuthority($authority);
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthority($inherit = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthority', [$inherit]);

        return parent::getAuthority($inherit);
    }

    /**
     * {@inheritDoc}
     */
    public function addMetadataUrl(\Mapbender\WmsBundle\Component\MetadataUrl $metadataUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMetadataUrl', [$metadataUrl]);

        return parent::addMetadataUrl($metadataUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function setMetadataUrl($metadataUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMetadataUrl', [$metadataUrl]);

        return parent::setMetadataUrl($metadataUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getMetadataUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMetadataUrl', []);

        return parent::getMetadataUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function addDimension($dimension)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDimension', [$dimension]);

        return parent::addDimension($dimension);
    }

    /**
     * {@inheritDoc}
     */
    public function setDimension($dimension)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDimension', [$dimension]);

        return parent::setDimension($dimension);
    }

    /**
     * {@inheritDoc}
     */
    public function getDimension()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDimension', []);

        return parent::getDimension();
    }

    /**
     * {@inheritDoc}
     */
    public function addDataUrl(\Mapbender\WmsBundle\Component\OnlineResource $dataUrl = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDataUrl', [$dataUrl]);

        return parent::addDataUrl($dataUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function setDataUrl($dataUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataUrl', [$dataUrl]);

        return parent::setDataUrl($dataUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataUrl', []);

        return parent::getDataUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function addFeatureListUrl(\Mapbender\WmsBundle\Component\OnlineResource $featureListUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFeatureListUrl', [$featureListUrl]);

        return parent::addFeatureListUrl($featureListUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function setFeatureListUrl($featureListUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFeatureListUrl', [$featureListUrl]);

        return parent::setFeatureListUrl($featureListUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getFeatureListUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFeatureListUrl', []);

        return parent::getFeatureListUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setKeywords(\Doctrine\Common\Collections\ArrayCollection $keywords)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKeywords', [$keywords]);

        return parent::setKeywords($keywords);
    }

    /**
     * {@inheritDoc}
     */
    public function getKeywords()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKeywords', []);

        return parent::getKeywords();
    }

    /**
     * {@inheritDoc}
     */
    public function addKeyword(\Mapbender\CoreBundle\Entity\Keyword $keyword)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addKeyword', [$keyword]);

        return parent::addKeyword($keyword);
    }

    /**
     * {@inheritDoc}
     */
    public function setPriority($priority)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPriority', [$priority]);

        return parent::setPriority($priority);
    }

    /**
     * {@inheritDoc}
     */
    public function getPriority()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPriority', []);

        return parent::getPriority();
    }

    /**
     * {@inheritDoc}
     */
    public function getClassname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClassname', []);

        return parent::getClassname();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getMergedBoundingBoxes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMergedBoundingBoxes', []);

        return parent::getMergedBoundingBoxes();
    }

}
